### ISSUE TITLE
Add support for creating an OpenApi3 object from a JsonNode

### ISSUE THREAD

**Issue by elliott-miller** [openapi4j/openapi4j#24]
**Is your feature request related to a problem? Please describe.**
I am preprocessing my OpenAPI document, by the time I come to parse it with `OpenApi3Parser` I already have a `JsonNode`. The current parser requires a file, which means I need to serilaise and write it to disk in order to get a `OpenApi3`

**Describe the solution you'd like**
Either add a method to `OpenApi3Parser` that takes a `JsonNode` or provide some other utility to do it

**Comment by llfbandit** [comment]
Hmm, in fact you already have all you need to do this.
As you already are processing the document with Jackson you should use the bindings to get the models.
For performance concern, you should (re-)use `TreeUtil.json` if needed since this is the `ObjectMapper` for the parser. `TreeUtil.json.convertValue(node, OpenApi3.class)` should do the trick in this case.

**Comment by elliott-miller** [comment]
Ah, ok. Understood. Closing
