### ISSUE TITLE
Relative url support in OAuthFlow Object

### ISSUE THREAD

**Issue by PierrePrimot** [openapi4j/openapi4j#71]
**Describe the bug**

Relative URLs are not allowed in the `authorizationUrl` field of the OAuth Flow Object.

**Expected behavior**

The specification indicates that

> **Relative References in URLs**
> Unless specified otherwise, all properties that are URLs MAY be relative references as defined by RFC3986. Relative references are resolved using the URLs defined in the Server Object as a Base URI.
> 

> The authorization URL to be used for this flow. This MUST be in the form of a URL.

As there is nothing special about this URL, I guess this field (and others) should be allowed to use relative paths. 

What do you think about it ?

**Comment by llfbandit** [comment]
Hi and welcome,

You're right, this needs to be addressed. Unfortunately, as first thought, this can lead to skip url validation on URL fields as I can't concat it directly to server URL description because of potential parameter variables. Maybe as URI only? I'll digg into it to see if it is enough jsut after the current work I'm on.

Thanks for the report.

**Comment by llfbandit** [comment]
Hi,
can you confirm the fix in latest 0.8-SNAPSHOT?

FYI, this fix has been extended to other models too (license, contact, ...).

**Comment by llfbandit** [comment]
Hi,
can you confirm the fix in latest 0.8-SNAPSHOT?

FYI, this fix has been extended to other models too (license, contact, ...).

**Comment by PierrePrimot** [comment]
Hello,

The fix is working perfectly in my case, thank you very much ! 👍
